export const DatosFicticios = [
    {
        idLinea: 1,
        linea: "MP05",
        eficiencia: 54,
        disponibilidad: 81,
        velocidad: 57,
        calidad: 78,
        productoTerminado: 2900,
    },
    {
        idLinea: 2,
        linea: "MP03",
        eficiencia: 47,
        disponibilidad: 43,
        velocidad: 90,
        calidad: 85,
        productoTerminado: 2600,
    },
    {
        idLinea: 3,
        linea: "MP02",
        eficiencia: 90,
        disponibilidad: 60,
        velocidad: 98,
        calidad: 54,
        productoTerminado: 2160,
    },
    {
        idLinea: 4,
        linea: "MP07",
        eficiencia: 74,
        disponibilidad: 30,
        velocidad: 40,
        calidad: 64,
        productoTerminado: 2460,
    },
    {
        idLinea: 5,
        linea: "MP06",
        eficiencia: 68,
        disponibilidad: 34,
        velocidad: 89,
        calidad: 45,
        productoTerminado: 2578,
    },
    {
        idLinea: 6,
        linea: "MP09",
        eficiencia: 24,
        disponibilidad: 70,
        velocidad: 97,
        calidad: 100,
        productoTerminado: 2587,
    },
];