export const DatosFicticios = [
    {
        status: 71,
        linea: "MP05",
        eficiencia: 54,
        disponibilidad: 81,
        velocidad: 57,
        calidad: 78,
        producto: 2900,
    },
    {
        status: 91,
        linea: "MP03",
        eficiencia: 47,
        disponibilidad: 43,
        velocidad: 90,
        calidad: 85,
        producto: 2600,
    },
    {
        status: 82,
        linea: "MP02",
        eficiencia: 90,
        disponibilidad: 60,
        velocidad: 98,
        calidad: 54,
        producto: 2160,
    },
    {
        status: 12,
        linea: "MP07",
        eficiencia: 74,
        disponibilidad: 30,
        velocidad: 40,
        calidad: 64,
        producto: 2460,
    },
    {
        status: 32,
        linea: "MP06",
        eficiencia: 68,
        disponibilidad: 34,
        velocidad: 89,
        calidad: 45,
        producto: 2578,
    },
    {
        status: 67,
        linea: "MP09",
        eficiencia: 24,
        disponibilidad: 70,
        velocidad: 97,
        calidad: 100,
        producto: 2587,
    },
];